EP_A/ProgrammingBlog/Controllers/AuthorController.cs
using ProgrammingBlog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProgrammingBlog.Controllers
{
    public class AuthorController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
      /*  // GET: Author
        public ActionResult Index()
        {
            return View();
        }*/

        // GET: Author/Details/5
        public ActionResult Details(string id)
        {
            List<BlogModel> blogModel = db.Blogs.Where(x => x.Users.Id == id).ToList();
            return View(blogModel);
        }
/*
        // GET: Author/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Author/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Author/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Author/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Author/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Author/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        */
    }
}

EP_A/ProgrammingBlog/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProgrammingBlog.Models;

namespace ProgrammingBlog.Controllers
{
    public class BlogController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Blog
        public ActionResult Index()
        {
            List<BlogModel> blogModels = new List<BlogModel>();
            List<BlogModel> latestsPosts = new List<BlogModel>();

            BlogCategoryModel blogCategoryModel = new BlogCategoryModel();

            //Gets the 5 most recent posts
            if (db.Blogs.Count() > 0 && db.Categories.Count() > 0)
            {
                blogModels = db.Blogs.OrderByDescending(x => x.dateTime).ToList();
                latestsPosts = blogModels.Take(5).ToList();
            }

            //populating empty entities according to their repsective blogs
            if (db.Blogs.Count() > 0 && db.Categories.Count() > 0)
            {
                blogCategoryModel.CSharp = db.Blogs.OrderByDescending(x => x.dateTime).Where(cSharp => cSharp.Category.CategoryTitle == "C#").ToList();
                blogCategoryModel.CSS = db.Blogs.OrderByDescending(x => x.dateTime).Where(css => css.Category.CategoryTitle == "CSS").ToList();
                blogCategoryModel.MVC = db.Blogs.OrderByDescending(x => x.dateTime).Where(mvc => mvc.Category.CategoryTitle == "MVC ASP.NET").ToList();
                blogCategoryModel.Javascript = db.Blogs.OrderByDescending(x => x.dateTime).Where(js => js.Category.CategoryTitle == "Javascript").ToList();
                blogCategoryModel.Blog = latestsPosts;
            }

            
              return View(blogCategoryModel);
        }
        
        
        public ActionResult SpecificCategory(string category) {
            if (category.Equals("C#"))
            {
                return RedirectToAction("CSharpBlogPosts", "Blog");
            }
            else if (category.Equals("Javascript"))
            {
                return RedirectToAction("JavascriptBlogPosts", "Blog");
            }
            else if (category.Equals("MVC ASP.NET"))
            {
                return RedirectToAction("MVCBlogPosts", "Blog");
            }
            else if (category.Equals("CSS"))
            {
                return RedirectToAction("CssBlogPosts", "Blog");
            }

            return RedirectToAction("Index", "Blog");

        }
        // GET: Blog
        public ActionResult CSharpBlogPosts()
        {
            BlogCategoryModel blogCategoryModel = new BlogCategoryModel();
            blogCategoryModel.CSharp = db.Blogs.OrderByDescending(x => x.dateTime).Where(cSharp => cSharp.Category.CategoryTitle == "C#").ToList();
            return View(blogCategoryModel);
        }

        // GET: Blog
        public ActionResult MVCBlogPosts()
        {
            BlogCategoryModel blogCategoryModel = new BlogCategoryModel();
            blogCategoryModel.MVC = db.Blogs.OrderByDescending(x => x.dateTime).Where(mvc => mvc.Category.CategoryTitle == "MVC ASP.NET").ToList();
            return View(blogCategoryModel);
        }

        // GET: Blog
        public ActionResult JavascriptBlogPosts()
        {
            BlogCategoryModel blogCategoryModel = new BlogCategoryModel();
            blogCategoryModel.Javascript = db.Blogs.OrderByDescending(x => x.dateTime).Where(js => js.Category.CategoryTitle == "Javascript").ToList();
            return View(blogCategoryModel);
        }

        // GET: Blog
        public ActionResult CssBlogPosts()
        {
            BlogCategoryModel blogCategoryModel = new BlogCategoryModel();
            blogCategoryModel.CSS = db.Blogs.OrderByDescending(x => x.dateTime).Where(css => css.Category.CategoryTitle == "CSS").ToList();
            return View(blogCategoryModel);
        }

        // GET: Blog/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogModel blogModel = db.Blogs.Find(id);
            if (blogModel == null)
            {
                return HttpNotFound();
            }
            return View(blogModel);
        }

        [Authorize]
        // GET: Blog/Create
        public ActionResult Create()
        {
            ViewBag.Categories = new SelectList(db.Categories, "CategoryID", "CategoryTitle");
            return View();
        }

        // POST: Blog/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BlogID,BlogHeading,BlogPost,BlogTags"), ] BlogModel blogModel, int CategoryId, HttpPostedFileBase imagePath)
        {

            blogModel.Users = db.Users.Where(x => x.UserName == System.Web.HttpContext.Current.User.Identity.Name).FirstOrDefault();
            blogModel.Category = db.Categories.Where(x => x.CategoryId == CategoryId).FirstOrDefault();
            blogModel.dateTime = DateTime.Now;
            if (ModelState.IsValid)
            {
                if ( imagePath != null)
                {
                    string absolutePath = Server.MapPath("\\BlogImages\\");
                    string relativePath = "\\BlogImages\\";
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(imagePath.FileName);
                    imagePath.SaveAs(absolutePath + fileName);//saving the image inside folder
                    blogModel.ImagePath = relativePath + fileName; //saving path inside the User instance that will be saved in db

                    db.Blogs.Add(blogModel);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    db.Blogs.Add(blogModel);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
              
            }

            return View(blogModel);
        }

        // GET: Blog/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogModel blogModel = db.Blogs.Find(id);
            if (blogModel == null)
            {
                return HttpNotFound();
            }
            ViewBag.Categories = new SelectList(db.Categories, "CategoryID", "CategoryTitle");
            return View(blogModel);
        }

        // POST: Blog/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "BlogID,BlogHeading,BlogPost,BlogTags")] BlogModel blogModel, int blogId, int CategoryId, HttpPostedFileBase imagePath)
        {
            blogModel.Users = db.Users.Where(x => x.UserName == System.Web.HttpContext.Current.User.Identity.Name).FirstOrDefault();
            blogModel.Category = db.Categories.Where(x => x.CategoryId == CategoryId).FirstOrDefault();
            blogModel.dateTime = DateTime.Now;
            blogModel.BlogID = blogId;
            if (ModelState.IsValid)
            {
                if (imagePath != null)
                {
                    string absolutePath = Server.MapPath("\\BlogImages\\");
                    string relativePath = "\\BlogImages\\";
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(imagePath.FileName);
                    imagePath.SaveAs(absolutePath + fileName);//saving the image inside folder
                    blogModel.ImagePath = relativePath + fileName; //saving path inside the User instance that will be saved in db
                    db.Entry(blogModel).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else { 
                db.Entry(blogModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
                }
            }
            return View(blogModel);
        }

        // GET: Blog/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogModel blogModel = db.Blogs.Find(id);
            if (blogModel == null)
            {
                return HttpNotFound();
            }
            return View(blogModel);
        }

        // POST: Blog/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogModel blogModel = db.Blogs.Find(id);
            db.Blogs.Remove(blogModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EP_A/ProgrammingBlog/Views/Blog/CSharpBlogPosts.cshtml
@model ProgrammingBlog.Models.BlogCategoryModel

@{
    ViewBag.Title = "C# Posts";
}

<h2>C# Posts</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div class="row">
    <div class="col-lg-9">
        <img src="@Model.CSharp[0].ImagePath" alt="Card image cap" width="450">
        <div>
            <h5>@Model.CSharp[0].BlogHeading</h5>
            <p>@Model.CSharp[0].BlogPost</p>
            <p>@Model.CSharp[0].Users.UserName</p>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="card">
            @for (int i = 1; i <= 4; i++)
            {
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">@Html.ActionLink(Model.CSharp[i].BlogHeading, "Details", new { id = Model.CSharp[i].BlogID })</li>
                </ul>
            }
        </div>
    </div>
</div>

<hr />

<table class="table">
    <tr>
        <th>
            <h1> Heading </h1>
        </th>
        <th>
            <h1>Posts</h1>
        </th>
        <th>
            <h1> Tags </h1>
        </th>
    </tr>
    @Html.Partial("_CSharpPostsPartial", Model)
</table>

EP_A/ProgrammingBlog/Views/Blog/Create.cshtml
@model ProgrammingBlog.Models.BlogModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Blog", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>BlogModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BlogHeading, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BlogHeading, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BlogHeading, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BlogPost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BlogPost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BlogPost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BlogTags, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BlogTags, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BlogTags, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", (IEnumerable<SelectListItem>)ViewBag.Categories, null, new { @class = "form-control" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" class="form-control" name="imagePath" />
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EP_A/ProgrammingBlog/Views/Blog/CssBlogPosts.cshtml
@model ProgrammingBlog.Models.BlogCategoryModel

@{
    ViewBag.Title = "CSS Posts";
}

<h2>CSS Posts</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div class="row">
    <div class="col-lg-9">
        <img src="@Model.CSS[0].ImagePath" alt="Card image cap" width="450">
        <div>
            <h5>@Model.CSS[0].BlogHeading</h5>
            <p>@Model.CSS[0].BlogPost</p>
            <p>@Model.CSS[0].Users.UserName</p>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="card">
            @for (int i = 1; i <= 4; i++)
            {
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">@Html.ActionLink(Model.CSS[i].BlogHeading, "Details", new { id = Model.CSS[i].BlogID })</li>
                </ul>
            }
        </div>
    </div>
</div>

<hr />

<table class="table">
    <tr>
        <th>
            <h1> Heading </h1>
        </th>
        <th>
            <h1>Posts</h1>
        </th>
        <th>
            <h1> Tags </h1>
        </th>
    </tr>
    @Html.Partial("_CSSPostsPartial", Model)
</table>

EP_A/ProgrammingBlog/Views/Blog/Delete.cshtml
@model ProgrammingBlog.Models.BlogModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BlogModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BlogHeading)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BlogHeading)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BlogPost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BlogPost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BlogTags)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BlogTags)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EP_A/ProgrammingBlog/Views/Blog/Details.cshtml
@model ProgrammingBlog.Models.BlogModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>BlogModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BlogHeading)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BlogHeading)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BlogPost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BlogPost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BlogTags)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BlogTags)
        </dd>
        <dd>
            <img src="@Model.ImagePath" width="250"/>
        </dd>
        <dd>
            @Html.ActionLink(Model.Category.CategoryTitle, "SpecificCategory", new { category = Model.Category.CategoryTitle })
        </dd>

        <dd>
            @Html.ActionLink(Model.Users.UserName, "Details", "Author", new { id = Model.Users.Id}, null)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BlogID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EP_A/ProgrammingBlog/Views/Blog/Edit.cshtml
@model ProgrammingBlog.Models.BlogModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Blog", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>BlogModel</h4>
    <hr />

    <div class="form-group">
        <div class="col-md-10">
            @Html.HiddenFor(model => model.BlogID)
        </div>
    </div>

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.BlogHeading, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BlogHeading, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BlogHeading, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BlogPost, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BlogPost, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BlogPost, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BlogTags, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BlogTags, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BlogTags, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategoryId", (IEnumerable<SelectListItem>)ViewBag.Categories, null, new { @class = "form-control" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" class="form-control" name="imagePath" />
            @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Edit" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EP_A/ProgrammingBlog/Views/Blog/Index.cshtml
@model ProgrammingBlog.Models.BlogCategoryModel

@{
    ViewBag.Title = "Index";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<h2>Index</h2>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->

    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <img src="@Model.Blog.FirstOrDefault().ImagePath" alt="">
            <div class="carousel-caption">
                <h3>@Model.Blog.FirstOrDefault().BlogHeading</h3>
            </div>
        </div>

        @for (int i = 1; i <= 4; i++)
        {
            <div class="item">
                <img src="@Model.Blog[i].ImagePath" alt="">
                <div class="carousel-caption">
                    <h3>@Model.Blog[i].BlogHeading</h3>
                </div>
            </div>
        }

    </div>
    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<br /> <br /> <br />
<br /> <br /> <br />
<br /> <br /> <br />

<div class="row">

        <div class="col-lg-4">
            <img src="@Model.CSharp[0].ImagePath" alt="Card image cap" width="250">
            <div>
                <h5>@Model.CSharp[0].BlogHeading</h5>
                <p>@Model.CSharp[0].BlogPost</p>
            </div>
        </div>
        <div class="col-lg-2">
            <div class="card">
                @for (int i = 1; i <= 4; i++)
                {
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">@Html.ActionLink(Model.CSharp[i].BlogHeading, "Details", new { id = Model.CSharp[i].BlogID })</li>
                    </ul>
                }
            </div>
        </div>

    <div class="col-lg-4">
        <img class="" src="@Model.CSS[0].ImagePath" alt="Card image cap" width="250">
        <div class="">
            <h5 class="">@Model.CSS[0].BlogHeading</h5>
            <p class="">@Model.CSS[0].BlogPost</p>
        </div>
    </div>
    <div class="col-lg-2">
        <div class="card">
            <!--List of  blog posts go here -->
            @for (int i = 1; i <= 4; i++)
            {
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">@Html.ActionLink(Model.CSS[i].BlogHeading, "Details", new { id = Model.CSS[i].BlogID })</li>
                </ul>
            }
        </div>
    </div>
</div>

<div class="row">
 
    <div class="col-lg-4">
        <div class="card">
            <img class="card-img-top" src="@Model.MVC[0].ImagePath" alt="Card image cap" width="250">
            <div class="card-body">
                <h5 class="card-title">@Model.MVC[0].BlogHeading</h5>
                <p class="card-text">@Model.MVC[0].BlogPost</p>
            </div>
        </div>
    </div>
    <div class="col-lg-2">
        <div class="card">
            <!-- List of blog posts go here -->
            @for (int i = 1; i <= 4; i++)
            {
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">@Html.ActionLink(Model.MVC[i].BlogHeading, "Details", new { id = Model.MVC[i].BlogID })</li>
                </ul>
            }
        </div>
    </div>


    <div class="col-lg-4">
        <div class="card">
            <img class="card-img-top" src="@Model.Javascript[0].ImagePath" alt="Card image cap" width="250">
            <div class="card-body">
                <h5 class="card-title">@Model.Javascript[0].BlogHeading</h5>
                <p class="card-text">@Model.Javascript[0].BlogPost</p>
            </div>
        </div>
    </div>
    <div class="col-lg-2">
        <div class="card">
            <!-- List of blog posts go here -->
            @for (int i = 1; i <= 4; i++)
            {
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">@Html.ActionLink(Model.Javascript[i].BlogHeading, "Details", new { id = Model.Javascript[i].BlogID })</li>
                </ul>
            }
        </div>
    </div>
</div>

EP_A/ProgrammingBlog/Views/Blog/JavascriptBlogPosts.cshtml
@model ProgrammingBlog.Models.BlogCategoryModel

@{
    ViewBag.Title = "Javascript Posts";
}

<h2>Javascript Posts</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div class="row">
    <div class="col-lg-9">
        <img src="@Model.Javascript[0].ImagePath" alt="Card image cap" width="450">
        <div>
            <h5>@Model.Javascript[0].BlogHeading</h5>
            <p>@Model.Javascript[0].BlogPost</p>
            <p>@Model.Javascript[0].Users.UserName</p>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="card">
            @for (int i = 1; i <= 4; i++)
            {
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">@Html.ActionLink(Model.Javascript[i].BlogHeading, "Details", new { id = Model.Javascript[i].BlogID })</li>
                </ul>
            }
        </div>
    </div>
</div>

<hr />

<table class="table">
    <tr>
        <th>
            <h1> Heading </h1>
        </th>
        <th>
            <h1>Posts</h1>
        </th>
        <th>
            <h1> Tags </h1>
        </th>
    </tr>
    @Html.Partial("_JavascriptPostsPartial", Model)
</table>